[capability]
index = "3"
[[capability.owners]]
index = "1"

[capability.owners.index_owners]
[[capability.owners.index_owners.owners]]
module = "ibc"
name = "ports/transfer"

[[capability.owners.index_owners.owners]]
module = "transfer"
name = "ports/transfer"

[[capability.owners]]
index = "2"

[capability.owners.index_owners]
[[capability.owners.index_owners.owners]]
module = "ibc"
name = "capabilities/ports/transfer/channels/channel-0"

[[capability.owners.index_owners.owners]]
module = "transfer"
name = "capabilities/ports/transfer/channels/channel-0"

[ibc.channel_genesis]
acknowledgements = []
commitments = []
next_channel_sequence = "1"
receipts = []
[[ibc.channel_genesis.ack_sequences]]
channel_id = "channel-0"
port_id = "transfer"
sequence = "1"

[[ibc.channel_genesis.channels]]
channel_id = "channel-0"
connection_hops = [ "connection-0",]
ordering = "ORDER_UNORDERED"
port_id = "transfer"
state = "STATE_OPEN"
version = "ics20-1"

[ibc.channel_genesis.channels.counterparty]
channel_id = "channel-0"
port_id = "transfer"
[[ibc.channel_genesis.recv_sequences]]
channel_id = "channel-0"
port_id = "transfer"
sequence = "1"

[[ibc.channel_genesis.send_sequences]]
channel_id = "channel-0"
port_id = "transfer"
sequence = "2"

[ibc.connection_genesis]
next_connection_sequence = "1"
[[ibc.connection_genesis.client_connection_paths]]
client_id = "07-tendermint-0"
paths = [ "connection-0",]

[[ibc.connection_genesis.connections]]
client_id = "07-tendermint-0"
delay_period = "0"
id = "connection-0"
state = "STATE_OPEN"
[[ibc.connection_genesis.connections.versions]]
features = [ "ORDER_ORDERED", "ORDER_UNORDERED",]
identifier = "1"


[ibc.connection_genesis.connections.counterparty]
client_id = "07-tendermint-0"
connection_id = "connection-0"
[ibc.connection_genesis.connections.counterparty.prefix]
key_prefix = "aWJj"

[ibc.connection_genesis.params]
max_expected_time_per_block = "30000000000"
